package dev.tggamesyt.xaeroseedmap.client.mixin;

import com.mojang.blaze3d.pipeline.RenderPipeline;
import com.mojang.blaze3d.platform.DepthTestFunction;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.textures.GpuTextureView;
import com.mojang.blaze3d.vertex.VertexFormat;
import dev.tggamesyt.xaeroseedmap.client.BiomeMapRenderer;
import dev.tggamesyt.xaeroseedmap.client.XaeroSeedMapClient;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gl.RenderPipelines;
import net.minecraft.client.gl.SimpleFramebuffer;
import net.minecraft.client.render.VertexFormats;
import net.minecraft.client.texture.AbstractTexture;
import net.minecraft.util.Identifier;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;
import xaero.map.graphics.ImprovedFramebuffer;
import xaero.map.gui.GuiMap;

import java.util.OptionalInt;

/**
 * Intercepts Xaero's render method just before it restores the default framebuffer.
 * At that point all tile textures are in primaryScaleFBO; we run a post-process pass
 * that replaces every very-dark pixel (unexplored black, or hover-darkened black) with
 * the seed-based biome map texture generated by {@link BiomeMapRenderer}.
 *
 * The biome texture has the same world-space extent as the FBO (1 pixel per MC chunk),
 * so sampling it at texCoord (0→1 over the FBO) gives exact per-chunk colouring.
 */
@Mixin(GuiMap.class)
public class GuiMapMixin {

    @Shadow(remap = false) private double cameraX;
    @Shadow(remap = false) private double cameraZ;
    @Shadow(remap = false) private double scale;

    /**
     * Pipeline: replaces very dark pixels with the biome map texture.
     * InSampler      = Xaero's rendered map FBO
     * WallpaperSampler = biome map texture
     */
    private static final RenderPipeline REPLACE_PIPELINE = RenderPipelines.register(
            RenderPipeline.builder()
                    .withLocation(Identifier.of("xaeroseedmap", "pipeline/replace_dark"))
                    .withVertexShader("core/blit_screen")
                    .withFragmentShader(Identifier.of("xaeroseedmap", "core/replace_dark"))
                    .withSampler("InSampler")
                    .withSampler("WallpaperSampler")
                    .withoutBlend()
                    .withDepthWrite(false)
                    .withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST)
                    .withColorWrite(true, true)
                    .withVertexFormat(VertexFormats.POSITION, VertexFormat.DrawMode.QUADS)
                    .build()
    );

    /** Ping-pong FBO — lazily created/resized to match Xaero's FBO. */
    private static SimpleFramebuffer tempFbo = null;

    @Redirect(
            method = "render",
            at = @At(
                    value = "INVOKE",
                    target = "Lxaero/map/graphics/ImprovedFramebuffer;bindDefaultFramebuffer(Lnet/minecraft/client/MinecraftClient;)V"
            )
    )
    private void redirectBindDefaultFramebuffer(ImprovedFramebuffer mapFbo, MinecraftClient mc) {
        if (mc.getTextureManager() != null) {
            // fboScale mirrors Xaero's internal scale calculation
            double fboScale = (scale >= 1.0) ? Math.max(1.0, Math.floor(scale)) : scale;

            boolean ready = BiomeMapRenderer.ensureTexture(
                    mc, cameraX, cameraZ,
                    mapFbo.textureWidth, mapFbo.textureHeight,
                    fboScale);

            if (ready) {
                AbstractTexture biomeTex = mc.getTextureManager().getTexture(XaeroSeedMapClient.BIOME_TEX_ID);
                GpuTextureView biomeView = biomeTex != null ? biomeTex.getGlTextureView() : null;

                if (biomeView != null) {
                    int w = mapFbo.textureWidth;
                    int h = mapFbo.textureHeight;
                    if (tempFbo == null || tempFbo.textureWidth != w || tempFbo.textureHeight != h) {
                        if (tempFbo != null) tempFbo.delete();
                        tempFbo = new SimpleFramebuffer("xaeroseedmap_temp", w, h, false);
                    }

                    var seqBuf = RenderSystem.getSequentialBuffer(VertexFormat.DrawMode.QUADS);
                    var indexBuffer = seqBuf.getIndexBuffer(6);
                    var vertexBuffer = RenderSystem.getQuadVertexBuffer();

                    // Step 1: post-process mapFbo + biome → tempFbo
                    var renderPass = RenderSystem.getDevice().createCommandEncoder()
                            .createRenderPass(
                                    () -> "xaeroseedmap_replace_dark",
                                    tempFbo.getColorAttachmentView(),
                                    OptionalInt.empty()
                            );
                    try {
                        renderPass.setPipeline(REPLACE_PIPELINE);
                        RenderSystem.bindDefaultUniforms(renderPass);
                        renderPass.setVertexBuffer(0, vertexBuffer);
                        renderPass.setIndexBuffer(indexBuffer, seqBuf.getIndexType());
                        renderPass.bindSampler("InSampler", mapFbo.getColorAttachmentView());
                        renderPass.bindSampler("WallpaperSampler", biomeView);
                        renderPass.drawIndexed(0, 0, 6, 1);
                    } finally {
                        renderPass.close();
                    }

                    // Step 2: copy result back into Xaero's FBO
                    tempFbo.drawBlit(mapFbo.getColorAttachmentView());
                }
            }
        }

        mapFbo.bindDefaultFramebuffer(mc);
    }
}
